Edit proposal
alexisljn/collab-media pull request #32
Opened 2020-02-26 20:02 UTC by alexisljn

2020-02-26 20:03 UTC, alexisljn commented on config/web.php
> +                'proposal/edit-proposal/<id:\d+>' => 'proposal/edit-proposal',
I'm going to change it in further commit

2020-02-26 20:05 UTC, alexisljn commented on views/proposal/my-proposal.php
> +            console.log(proposalContent);
Will be removed of course ;)

2020-02-27 15:03 UTC, EmileCalixte requested changes

2020-02-27 15:03 UTC, EmileCalixte commented on controllers/ProposalController.php
> +        count($editedProposal->proposalContentHistories)-1];
Please indent this line

2020-02-27 15:03 UTC, EmileCalixte commented on controllers/ProposalController.php
> +        $model->content = $postRequest['ManageProposalForm']['content'];
Those two lines are useless: The $model->load function already does this

2020-02-27 15:03 UTC, EmileCalixte commented on controllers/ProposalController.php
> +                $this->saveEditedProposal($postRequest['ManageProposalForm']['title'], $editedProposal);
Why don't you use $model->title instead of $postRequest['ManageProposalForm']['title'] ?

2020-02-27 15:03 UTC, EmileCalixte commented on controllers/ProposalController.php
> +                if ($postRequest['ManageProposalForm']['content'] != $lastProposalContent->content) {
Idem, you should use $model->content

2020-02-27 15:03 UTC, EmileCalixte commented on controllers/ProposalController.php
> +                    $this->saveProposalContent($postRequest['ManageProposalForm']['content'], $editedProposal, false);
Idem

2020-02-27 15:03 UTC, EmileCalixte commented on controllers/ProposalController.php
> +        $file = $proposal->files[0];
We have to edit the database model : a proposal have maximum 1 file, so the field proposal_id in the file table must be unique

2020-02-27 15:03 UTC, EmileCalixte commented on controllers/ProposalController.php
> +        $file = $proposal->files[0];
After that, you will have to use $file = $proposal->file

2020-02-27 15:07 UTC, GuenoleCHERUBIN requested changes

2020-02-27 15:07 UTC, GuenoleCHERUBIN commented on controllers/ProposalController.php
> +        throw new $unauthorizedException();
Why $unauthorizedException ?

2020-02-27 15:07 UTC, GuenoleCHERUBIN commented on controllers/ProposalController.php
> +
Missing an else ?

2020-02-27 15:07 UTC, GuenoleCHERUBIN commented on sql/import.sql
> +-- Base de données :  `collabmedia`
To much spaces ?

2020-02-27 15:07 UTC, GuenoleCHERUBIN commented on views/proposal/my-proposal.php
> +
Why so much return ?

2020-02-27 15:25 UTC, EmileCalixte approved these changes

2020-02-27 15:25 UTC, GuenoleCHERUBIN approved these changes

2020-02-27 15:41 UTC, merged